CREATE TABLE [dbo].[TBL_SCMS_VIEWS_BY_PROFILE]
( 
    [profile] INT NOT NULL, 
    [view] INT NOT NULL, 
    [can_read] BIT NOT NULL DEFAULT 0, 
    [can_insert] BIT NOT NULL DEFAULT 0, 
    [can_update] BIT NOT NULL DEFAULT 0, 
    [can_delete] BIT NOT NULL DEFAULT 0, 
    [created_by] NVARCHAR(20) NOT NULL, 
    [created_at] DATETIME NOT NULL DEFAULT GETDATE(), 
    [modified_by] NVARCHAR(20) NULL, 
    [modified_at] DATETIME NULL, 
    [is_active] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT [FK_TBL_SCMS_VIEWS_BY_PROFILE_TBL_SCMS_VIEW] FOREIGN KEY ([view]) REFERENCES [TBL_SCMS_VIEW]([id]),
	CONSTRAINT [FK_TBL_SCMS_VIEWS_BY_PROFILE_TBL_SCMS_USER_CRE] FOREIGN KEY (created_by) REFERENCES [TBL_SCMS_USER]([user_id]), 
    CONSTRAINT [FK_TBL_VIEWS_BY_SCMS_PROFILE_TBL_SCMS-USER_MOD] FOREIGN KEY (modified_by) REFERENCES [TBL_SCMS_USER]([user_id]), 
    CONSTRAINT [PK_TBL_SCMS_VIEWS_BY_PROFILE] PRIMARY KEY ([profile], [view]), 
    CONSTRAINT [FK_TBL_SCMS_VIEWS_BY_PROFILE_TBL_SCMS_PROFILE] FOREIGN KEY ([profile]) REFERENCES [TBL_SCMS_PROFILE]([id]) 
)
