CREATE TABLE [dbo].[TBL_PM_COMPONENT_REPLACEMENT]
(
	cmprpl_id_Pk	BIGINT IDENTITY PRIMARY KEY NOT NULL,
cmprpl_external_identifier	NVARCHAR(500) NOT NULL,
cmprpl_task_Fk	BIGINT NOT NULL,
cmprpl_material_Fk	BIGINT NOT NULL,
cmprpl_replaced_material_Fk	BIGINT NOT NULL,
[cmprpl_comments] NVARCHAR(MAX) NULL, 
    CONSTRAINT [FK_TBL_PM_COMPONENT_REPLACEMENT_TBL_PM_TASK_id] FOREIGN KEY ([cmprpl_task_Fk]) REFERENCES [TBL_PM_TASK]([tsk_id_Pk]), 
CONSTRAINT [FK_TBL_PM_COMPONENT_REPLACEMENT_TBL_PM_MATERIAL_id] FOREIGN KEY ([cmprpl_material_Fk]) REFERENCES [TBL_PM_MATERIAL]([mtr_id_Pk]), 
CONSTRAINT [FK_TBL_PM_COMPONENT_REPLACEMENT_TBL_PM_MATERIAL_id_replacemd] FOREIGN KEY ([cmprpl_replaced_material_Fk]) REFERENCES [TBL_PM_MATERIAL]([mtr_id_Pk])
)
