CREATE TABLE [dbo].[TBL_FAM_AVAILABILITY_FORECAST_ITEM]
(
	avlfrcitm_id_Pk	BIGINT PRIMARY KEY NOT NULL,
avlfrcitm_fixed_asset_Fk	BIGINT NOT NULL,
avlfrcitm_stock	INT NOT NULL,
avlfrcitm_status	NVARCHAR(100) NOT NULL,
avlfrcitm_from	DATETIME NOT NULL,
avlfrcitm_to	DATETIME NOT NULL,
avlfrcitm_availability_forecast_Fk	BIGINT NOT NULL,
CONSTRAINT [FK_TBL_FAM_AVAILABILITY_FORECAST_ITEM_TBL_FAM_AVAILABILITY_FORECAST] FOREIGN KEY ([avlfrcitm_availability_forecast_Fk]) REFERENCES [TBL_FAM_AVAILABILITY_FORECAST]([avlfrc_id_Pk]),
CONSTRAINT [FK_TBL_FAM_AVAILABILITY_FORECAST_ITEM_TBL_FAM_FIXEDASSET] FOREIGN KEY ([avlfrcitm_fixed_asset_Fk]) REFERENCES [TBL_FAM_FIXEDASSET]([fxdast_id_Pk])

)
