CREATE TABLE [dbo].[TBL_PM_MEASURE]
(
	msr_id_Pk	BIGINT IDENTITY PRIMARY KEY NOT NULL, 
msr_unity_of_measurement	NVARCHAR(500) NOT NULL,
msr_value	NVARCHAR(500) NULL,
msr_external_identifier	NVARCHAR(500) NOT NULL,
msr_comments	NVARCHAR(500) NULL,
msr_document_Fk	BIGINT NOT NULL,
msr_device_type	NVARCHAR(20) NOT NULL,
[msr_technical_object_Fk] BIGINT NOT NULL, 
    CONSTRAINT [FK_TBL_PM_MEASURE_TBL_PM_MEASUREMENT_DOCUMENT] FOREIGN KEY ([msr_document_Fk]) REFERENCES [TBL_PM_MEASUREMENT_DOCUMENT]([msrdcm_id_Pk]),
	CONSTRAINT [FK_TBL_PM_MEASURE_TBL_PM_TECHNICALOBJECT] FOREIGN KEY ([msr_technical_object_Fk]) REFERENCES [TBL_PM_TECHNICALOBJECT]([tchobj_id_Pk])
)
