CREATE TABLE [dbo].[TBL_SRA_EMPLOYEE]
(
	[id] INT NOT NULL PRIMARY KEY, 
    [role] NVARCHAR(250) NULL, 
    [area] NVARCHAR(250) NULL, 
    [person] INT NOT NULL, 
    [contact] INT NOT NULL, 
    [user] NVARCHAR(20) NOT NULL, 
    [hired_at] DATETIME NOT NULL, 
    [supervisor] INT NOT NULL, 
    [comments] NVARCHAR(MAX) NULL, 
    [image_url] NVARCHAR(MAX) NULL, 
    CONSTRAINT [FK_TBL_SRA_EMPLOYEE_TBL_SCMS_PERSON] FOREIGN KEY ([person]) REFERENCES [TBL_SRA_PERSON]([id]), 
    CONSTRAINT [FK_TBL_SRA_EMPLOYEE_TBL_SCMS_CONTACT] FOREIGN KEY ([contact]) REFERENCES [TBL_SRA_CONTACT]([id]), 
    CONSTRAINT [FK_TBL_SRA_EMPLOYEE_TBL_SCMS_USER] FOREIGN KEY ([user]) REFERENCES [TBL_SCMS_USER]([user_id]), 
    CONSTRAINT [FK_TBL_SRA_EMPLOYEE_TBL_SCMS_USER_SUP] FOREIGN KEY ([supervisor]) REFERENCES [TBL_SRA_EMPLOYEE]([id]), 
    CONSTRAINT [AK_TBL_SRA_EMPLOYEE_TBL_SCMS_USER] UNIQUE ([user])
)
