CREATE TABLE [dbo].[TBL_FAM_PURCHASE_REQUEST]
(
	prcrqs_id_Pk	BIGINT PRIMARY KEY NOT NULL,
prcrqs_number	VARCHAR(MAX) NOT NULL, 
prcrqs_informed_Fk	INT NOT NULL,
prcrqs_responsible_Fk	INT NOT NULL,
prcrqs_accountable_Fk	INT NOT NULL,
prcrqs_details	NVARCHAR(500) NOT NULL,
prcrqs_type_Fk	BIGINT NOT NULL,
prcrqs_topic	NVARCHAR(50) NOT NULL,
prcrqs_registered_at	DATETIME NOT NULL,
prcrqs_updated_at	DATETIME NOT NULL, 
prcrqs_status	NVARCHAR(10) NOT NULL, 
prcrqs_comments	NVARCHAR(500) NULL,
prcrqs_external_identifier	NVARCHAR(500) NOT NULL,
prcrqs_novelty_Fk	BIGINT NOT NULL,
prcrqs_fixed_asset_Fk	BIGINT NOT NULL,
CONSTRAINT [FK_TBL_FAM_PURCHASE_REQUEST_TBL_SRA_EMPLOYEE_APP] FOREIGN KEY ([prcrqs_informed_Fk]) REFERENCES [TBL_SRA_EMPLOYEE]([id]), 
CONSTRAINT [FK_TBL_FAM_PURCHASE_REQUEST_TBL_SRA_EMPLOYEE_RES] FOREIGN KEY ([prcrqs_responsible_Fk]) REFERENCES [TBL_SRA_EMPLOYEE]([id]), 
CONSTRAINT [FK_TBL_FAM_PURCHASE_REQUEST_TBL_SRA_EMPLOYEE_ACC] FOREIGN KEY ([prcrqs_accountable_Fk]) REFERENCES [TBL_SRA_EMPLOYEE]([id]),
CONSTRAINT [FK_TBL_FAM_PURCHASE_REQUEST_TBL_FAM_NOVELTY] FOREIGN KEY ([prcrqs_novelty_Fk]) REFERENCES [TBL_FAM_NOVELTY]([nvlrqs_id_Pk]),
CONSTRAINT [FK_TBL_FAM_PURCHASE_REQUEST_TBL_FAM_FIXEDASSET] FOREIGN KEY ([prcrqs_fixed_asset_Fk]) REFERENCES [TBL_FAM_FIXEDASSET]([fxdast_id_Pk])


)
