CREATE TABLE [dbo].[TBL_SCMS_PARAM]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [category] INT NOT NULL, 
    [value] NVARCHAR(MAX) NOT NULL, 
    [description] NVARCHAR(250) NOT NULL, 
    [order] INT NOT NULL, 
    [is_active] BIT NOT NULL DEFAULT 1, 
    [created] DATETIME NOT NULL DEFAULT GETDATE(), 
    [created_by] NVARCHAR(20) NOT NULL, 
    [modified] DATETIME NULL, 
    [modified_by] NVARCHAR(20) NULL, 
    [external_id] NVARCHAR(50) NULL, 
    [comments] NVARCHAR(250) NULL, 
    CONSTRAINT [FK_TBL_SCMS_PARAM_TBL_SCMS_PARAM_CATEGORY] FOREIGN KEY ([category]) REFERENCES [TBL_SCMS_PARAM_CATEGORY]([id]), 
    CONSTRAINT [FK_TBL_SCMS_PARAM_TBL_SCMS_USER] FOREIGN KEY (created_by) REFERENCES [TBL_SCMS_USER]([user_id]), 
    CONSTRAINT [FK_TBL_SCMS_PARAM_TBL_SCMS-USER_2] FOREIGN KEY (modified_by) REFERENCES [TBL_SCMS_USER]([user_id])
)
