CREATE TABLE [dbo].[TBL_SCMS_ROLE]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [name] NVARCHAR(50) NOT NULL, 
    [description] NVARCHAR(250) NULL, 
    [is_active] BIT NOT NULL DEFAULT 0, 
    [created_by] NVARCHAR(20) NOT NULL, 
    [created_at] DATETIME NOT NULL DEFAULT GETDATE(), 
    [modified_by] NVARCHAR(20) NULL, 
    [modified_at] DATETIME NULL,
	[app] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [FK_TBL_SCMS_ROLE_TBL_SCMS_USER_CRE] FOREIGN KEY (created_by) REFERENCES [TBL_SCMS_USER]([user_id]), 
    CONSTRAINT [FK_TBL_SCMS_ROLE_TBL_SCMS-USER_MOD] FOREIGN KEY (modified_by) REFERENCES [TBL_SCMS_USER]([user_id]), 
    CONSTRAINT [FK_TBL_SCMS_ROLE_TBL_SCMS_APP] FOREIGN KEY ([app]) REFERENCES [TBL_SCMS_APP]([id]) 
)
