CREATE TABLE [dbo].[TBL_SCMS_VIEW]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [name] NVARCHAR(100) NOT NULL, 
    [description] NVARCHAR(250) NOT NULL, 
    [parent] INT NULL, 
    [app] NVARCHAR(50) NOT NULL, 
    [is_enabled] BIT NOT NULL, 
    [approved_by] NVARCHAR(20) NULL, 
    [approved_at] DATETIME NULL, 
    CONSTRAINT [FK_TBL_SCMS_VIEW_TBL_SCMS_VIEW] FOREIGN KEY (parent) REFERENCES [TBL_SCMS_VIEW]([id]), 
    CONSTRAINT [FK_TBL_SCMS_VIEW_TBL_SCMS_APP] FOREIGN KEY (app) REFERENCES [TBL_SCMS_APP]([id]),
	CONSTRAINT [FK_TBL_SCMS_VIEW_TBL_SCMS_USER] FOREIGN KEY (approved_by) REFERENCES [TBL_SCMS_USER]([user_id]) 
)
