CREATE TABLE [dbo].[TBL_SCMS_USERS_BY_ROLE]
(
	[role] INT NOT NULL , 
    [user] NVARCHAR(20) NOT NULL, 
    [created_at] DATETIME NOT NULL DEFAULT GETDATE(), 
    [created_by] NVARCHAR(20) NOT NULL, 
    [modified_at] DATETIME NULL, 
    [modified_by] NVARCHAR(20) NULL, 
    [is_active] BIT NOT NULL DEFAULT 0, 
    PRIMARY KEY ([role], [user]), 
    CONSTRAINT [FK_TBL_SCMS_USERS_BY_ROLE_TBL_SCMS_ROLE] FOREIGN KEY ([role]) REFERENCES [TBL_SCMS_ROLE]([id]), 
    CONSTRAINT [FK_TBL_SCMS_USERS_BY_ROLE_TBL_SCMS_USER] FOREIGN KEY ([user]) REFERENCES [TBL_SCMS_USER]([user_id]), 
    CONSTRAINT [FK_TBL_SCMS_USERS_BY_ROLE_TBL_SCMS_USER_CRE] FOREIGN KEY (created_by) REFERENCES [TBL_SCMS_USER]([user_id]), 
    CONSTRAINT [FK_TBL_SCMS_USERS_BY_ROLE_TBL_SCMS-USER_MOD] FOREIGN KEY (modified_by) REFERENCES [TBL_SCMS_USER]([user_id])
)
