CREATE TABLE [dbo].[TBL_FAM_AVAILABILITY_FORECAST]
(
	[avlfrc_id_Pk] BIGINT NOT NULL PRIMARY KEY, 
    [avlfrc_request_Fk] BIGINT NOT NULL, 
    [avlfrc_generated_at] DATETIME NOT NULL, 
    [avlfrc_valid_until] DATETIME NOT NULL, 
    [avlfrc_validated_by_Fk] INT NOT NULL,
	CONSTRAINT [FK_TBL_FAM_AVAILABILITY_FORECAST_TBL_SRA_EMPLOYEE_APP] FOREIGN KEY ([avlfrc_validated_by_Fk]) REFERENCES [TBL_SRA_EMPLOYEE]([id]),
	CONSTRAINT [FK_TBL_FAM_AVAILABILITY_FORECAST_TBL_FAM_REQUEST] FOREIGN KEY ([avlfrc_request_Fk]) REFERENCES [TBL_FAM_REQUEST]([rqs_id_Pk])
)
