CREATE TABLE [dbo].[TBL_SCMS_PARAM_CATEGORY]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [name] NVARCHAR(50) NOT NULL, 
    [description] NVARCHAR(MAX) NULL, 
    [type] INT NOT NULL,  
    [created] DATETIME NOT NULL DEFAULT GETDATE(), 
    [created_by] NVARCHAR(20) NOT NULL, 
    [modified] DATETIME NULL, 
    [modified_by] NVARCHAR(20) NULL, 
    CONSTRAINT [FK_TBL_SCMS_PARAM_TBL_SCMS_PARAM_TYPE] FOREIGN KEY ([type]) REFERENCES [TBL_SCMS_PARAM_TYPE]([id]), 
    CONSTRAINT [FK_TBL_SCMS_PARAM_CAT_TBL_SCMS_USER] FOREIGN KEY (created_by) REFERENCES [TBL_SCMS_USER]([user_id]), 
    CONSTRAINT [FK_TBL_SCMS_PARAM_CAT_TBL_SCMS-USER_2] FOREIGN KEY (modified_by) REFERENCES [TBL_SCMS_USER]([user_id])
)