CREATE PROCEDURE [dbo].[spFAMUpdateInventory]
	@fa_inventory_number NVARCHAR(20), 
	@fa_number NVARCHAR(20), 
	@fa_subnumber NVARCHAR(20), 
	@fa_denomination NVARCHAR(50), 
	@fa_class NVARCHAR(50), 
	@fa_type NVARCHAR(50), 
	@fa_sn NVARCHAR(20), 
	@fa_removal_mark BIT, 
	@fa_entry_locked BIT, 
	@fa_cost_center INT, 
	@fa_profit_center INT, 
	@fa_usage NVARCHAR(50), 
	@fa_supernumber NVARCHAR(50), 
	@fa_capitalization_at DATETIME, 
	@fa_decapitalization_at DATETIME, 
	@fa_last_disposal_at DATETIME, 
	@fa_entry_at DATETIME, 
	@fa_created_at DATETIME, 
	@fa_created_by NVARCHAR(20), 
	@fa_modified_at DATETIME, 
	@fa_modified_by NVARCHAR(20), 
	@fa_state NVARCHAR(20)
AS
	UPDATE [TBL_FAM_INVENTORY]
	SET
		[TBL_FAM_INVENTORY].[fa_number] = @fa_number,
		[TBL_FAM_INVENTORY].[fa_subnumber] = @fa_subnumber,
		[TBL_FAM_INVENTORY].[fa_denomination] = @fa_denomination,
		[TBL_FAM_INVENTORY].[fa_class] = @fa_class,
		[TBL_FAM_INVENTORY].[fa_type] = @fa_type,
		[TBL_FAM_INVENTORY].[fa_sn] = @fa_sn,
		[TBL_FAM_INVENTORY].[fa_removal_mark] = @fa_removal_mark,
		[TBL_FAM_INVENTORY].[fa_entry_locked] = @fa_entry_locked,
		[TBL_FAM_INVENTORY].[fa_cost_center] = @fa_cost_center,
		[TBL_FAM_INVENTORY].[fa_profit_center] = @fa_profit_center,
		[TBL_FAM_INVENTORY].[fa_usage] = @fa_usage,
		[TBL_FAM_INVENTORY].[fa_supernumber]= @fa_supernumber,
		[TBL_FAM_INVENTORY].[fa_capitalization_at] = @fa_capitalization_at,
		[TBL_FAM_INVENTORY].[fa_decapitalization_at] = @fa_decapitalization_at,
		[TBL_FAM_INVENTORY].[fa_last_disposal_at] = @fa_last_disposal_at,
		[TBL_FAM_INVENTORY].[fa_entry_at] = @fa_entry_at,
		[TBL_FAM_INVENTORY].[fa_created_at] = @fa_created_at,
		[TBL_FAM_INVENTORY].[fa_created_by] = @fa_created_by,
		[TBL_FAM_INVENTORY].[fa_modified_at] = @fa_modified_at,
		[TBL_FAM_INVENTORY].[fa_modified_by] = @fa_modified_by,
		[TBL_FAM_INVENTORY].[fa_state] = @fa_state
	WHERE
		[TBL_FAM_INVENTORY].[fa_inventory_number] = @fa_inventory_number
RETURN 0
