//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOFTTEK.SCMS.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SCMS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SCMS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SOFTTEK.SCMS.Data.SCMS", typeof(SCMS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMAddAvailabilityForecast.
        /// </summary>
        internal static string FA_SP_Insert_AvailabilityForecast {
            get {
                return ResourceManager.GetString("FA_SP_Insert_AvailabilityForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMAddAvailabilityForecastItem.
        /// </summary>
        internal static string FA_SP_Insert_AvailabilityForecastItem {
            get {
                return ResourceManager.GetString("FA_SP_Insert_AvailabilityForecastItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMAddFixedAsset.
        /// </summary>
        internal static string FA_SP_Insert_FixedAsset {
            get {
                return ResourceManager.GetString("FA_SP_Insert_FixedAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMAddNovelty.
        /// </summary>
        internal static string FA_SP_Insert_NoveltyRequest {
            get {
                return ResourceManager.GetString("FA_SP_Insert_NoveltyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMAddInventoryTaking.
        /// </summary>
        internal static string FA_SP_Insert_PhysicalInventoryTaking {
            get {
                return ResourceManager.GetString("FA_SP_Insert_PhysicalInventoryTaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMAddInventoryItem.
        /// </summary>
        internal static string FA_SP_Insert_PhysicalInventoryTakingItem {
            get {
                return ResourceManager.GetString("FA_SP_Insert_PhysicalInventoryTakingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMAddProvider.
        /// </summary>
        internal static string FA_SP_Insert_Provider {
            get {
                return ResourceManager.GetString("FA_SP_Insert_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMAddPurchaseRequest.
        /// </summary>
        internal static string FA_SP_Insert_PurchaseRequest {
            get {
                return ResourceManager.GetString("FA_SP_Insert_PurchaseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMAddRequest.
        /// </summary>
        internal static string FA_SP_Insert_Request {
            get {
                return ResourceManager.GetString("FA_SP_Insert_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMAddRetirement.
        /// </summary>
        internal static string FA_SP_Insert_RetirementRequest {
            get {
                return ResourceManager.GetString("FA_SP_Insert_RetirementRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMAddTecnicalEvaluationRequest.
        /// </summary>
        internal static string FA_SP_Insert_TechnicalEvaluationRequest {
            get {
                return ResourceManager.GetString("FA_SP_Insert_TechnicalEvaluationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMAddTransferRequest.
        /// </summary>
        internal static string FA_SP_Insert_TransferRequest {
            get {
                return ResourceManager.GetString("FA_SP_Insert_TransferRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMAddWorkOrder.
        /// </summary>
        internal static string FA_SP_Insert_WorkOrder {
            get {
                return ResourceManager.GetString("FA_SP_Insert_WorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMGetAvailabilityForecast.
        /// </summary>
        internal static string FA_SP_Select_AvailabilityForecast {
            get {
                return ResourceManager.GetString("FA_SP_Select_AvailabilityForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMGetAvailabilityForecastItem.
        /// </summary>
        internal static string FA_SP_Select_AvailabilityForecastItem {
            get {
                return ResourceManager.GetString("FA_SP_Select_AvailabilityForecastItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMGetFixedAssetById.
        /// </summary>
        internal static string FA_SP_Select_FixedAsset {
            get {
                return ResourceManager.GetString("FA_SP_Select_FixedAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMGetNovelty.
        /// </summary>
        internal static string FA_SP_Select_NoveltyRequest {
            get {
                return ResourceManager.GetString("FA_SP_Select_NoveltyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMGetInventoryTaking.
        /// </summary>
        internal static string FA_SP_Select_PhysicalInventoryTaking {
            get {
                return ResourceManager.GetString("FA_SP_Select_PhysicalInventoryTaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMGetInventoryItem.
        /// </summary>
        internal static string FA_SP_Select_PhysicalInventoryTakingItem {
            get {
                return ResourceManager.GetString("FA_SP_Select_PhysicalInventoryTakingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMGetProvider.
        /// </summary>
        internal static string FA_SP_Select_Provider {
            get {
                return ResourceManager.GetString("FA_SP_Select_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMGetPurchaseRequest.
        /// </summary>
        internal static string FA_SP_Select_PurchaseRequest {
            get {
                return ResourceManager.GetString("FA_SP_Select_PurchaseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMGetRequest.
        /// </summary>
        internal static string FA_SP_Select_Request {
            get {
                return ResourceManager.GetString("FA_SP_Select_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMGetRetirement.
        /// </summary>
        internal static string FA_SP_Select_RetirementRequest {
            get {
                return ResourceManager.GetString("FA_SP_Select_RetirementRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMGetTecnicalEvaluationRequest.
        /// </summary>
        internal static string FA_SP_Select_TechnicalEvaluationRequest {
            get {
                return ResourceManager.GetString("FA_SP_Select_TechnicalEvaluationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMGetTransferRequest.
        /// </summary>
        internal static string FA_SP_Select_TransferRequest {
            get {
                return ResourceManager.GetString("FA_SP_Select_TransferRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMGetWorkOrder.
        /// </summary>
        internal static string FA_SP_Select_WorkOrder {
            get {
                return ResourceManager.GetString("FA_SP_Select_WorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMUpdateAvailabilityForecast.
        /// </summary>
        internal static string FA_SP_Update_AvailabilityForecast {
            get {
                return ResourceManager.GetString("FA_SP_Update_AvailabilityForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMUpdateAvailabilityForecastItem.
        /// </summary>
        internal static string FA_SP_Update_AvailabilityForecastItem {
            get {
                return ResourceManager.GetString("FA_SP_Update_AvailabilityForecastItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMUpdateFixedAsset.
        /// </summary>
        internal static string FA_SP_Update_FixedAsset {
            get {
                return ResourceManager.GetString("FA_SP_Update_FixedAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMUpdateNovelty.
        /// </summary>
        internal static string FA_SP_Update_NoveltyRequest {
            get {
                return ResourceManager.GetString("FA_SP_Update_NoveltyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMUpdateInventoryTaking.
        /// </summary>
        internal static string FA_SP_Update_PhysicalInventoryTaking {
            get {
                return ResourceManager.GetString("FA_SP_Update_PhysicalInventoryTaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMUpdateInventoryItem.
        /// </summary>
        internal static string FA_SP_Update_PhysicalInventoryTakingItem {
            get {
                return ResourceManager.GetString("FA_SP_Update_PhysicalInventoryTakingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMUpdateProvider.
        /// </summary>
        internal static string FA_SP_Update_Provider {
            get {
                return ResourceManager.GetString("FA_SP_Update_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMUpdatePurchaseRequest.
        /// </summary>
        internal static string FA_SP_Update_PurchaseRequest {
            get {
                return ResourceManager.GetString("FA_SP_Update_PurchaseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMUpdateRequest.
        /// </summary>
        internal static string FA_SP_Update_Request {
            get {
                return ResourceManager.GetString("FA_SP_Update_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMUpdateRetirement.
        /// </summary>
        internal static string FA_SP_Update_Retirement {
            get {
                return ResourceManager.GetString("FA_SP_Update_Retirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMUpdateRetirement.
        /// </summary>
        internal static string FA_SP_Update_RetirementRequest {
            get {
                return ResourceManager.GetString("FA_SP_Update_RetirementRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMUpdateTecnicalEvaluationRequest.
        /// </summary>
        internal static string FA_SP_Update_TechnicalEvaluationRequest {
            get {
                return ResourceManager.GetString("FA_SP_Update_TechnicalEvaluationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMUpdateTransferRequest.
        /// </summary>
        internal static string FA_SP_Update_TransferRequest {
            get {
                return ResourceManager.GetString("FA_SP_Update_TransferRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spFAMUpdateWorkOrder.
        /// </summary>
        internal static string FA_SP_Update_WorkOrder {
            get {
                return ResourceManager.GetString("FA_SP_Update_WorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMAddActivity.
        /// </summary>
        internal static string PM_SP_Insert_Activity {
            get {
                return ResourceManager.GetString("PM_SP_Insert_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMAddAdvice.
        /// </summary>
        internal static string PM_SP_Insert_Advice {
            get {
                return ResourceManager.GetString("PM_SP_Insert_Advice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMAddComponentReplacement.
        /// </summary>
        internal static string PM_SP_Insert_ComponentReplacement {
            get {
                return ResourceManager.GetString("PM_SP_Insert_ComponentReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMAddEquipment.
        /// </summary>
        internal static string PM_SP_Insert_Equipment {
            get {
                return ResourceManager.GetString("PM_SP_Insert_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMAddMaintenancePlan.
        /// </summary>
        internal static string PM_SP_Insert_MaintenancePlan {
            get {
                return ResourceManager.GetString("PM_SP_Insert_MaintenancePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMAddMaterial.
        /// </summary>
        internal static string PM_SP_Insert_Material {
            get {
                return ResourceManager.GetString("PM_SP_Insert_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMAddMeasure.
        /// </summary>
        internal static string PM_SP_Insert_Measure {
            get {
                return ResourceManager.GetString("PM_SP_Insert_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMAddMeasurementDocument.
        /// </summary>
        internal static string PM_SP_Insert_MeasurementDocument {
            get {
                return ResourceManager.GetString("PM_SP_Insert_MeasurementDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMAddTask.
        /// </summary>
        internal static string PM_SP_Insert_Task {
            get {
                return ResourceManager.GetString("PM_SP_Insert_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMAddTechnicalLocation.
        /// </summary>
        internal static string PM_SP_Insert_TechnicalLocation {
            get {
                return ResourceManager.GetString("PM_SP_Insert_TechnicalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMAddTechnicalObject.
        /// </summary>
        internal static string PM_SP_Insert_TechnicalObject {
            get {
                return ResourceManager.GetString("PM_SP_Insert_TechnicalObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMAddWorkOrder.
        /// </summary>
        internal static string PM_SP_Insert_WorkOrder {
            get {
                return ResourceManager.GetString("PM_SP_Insert_WorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMGetActivity.
        /// </summary>
        internal static string PM_SP_Select_Activity {
            get {
                return ResourceManager.GetString("PM_SP_Select_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMGetAdvice.
        /// </summary>
        internal static string PM_SP_Select_Advice {
            get {
                return ResourceManager.GetString("PM_SP_Select_Advice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMGetComponentReplacement.
        /// </summary>
        internal static string PM_SP_Select_ComponentReplacement {
            get {
                return ResourceManager.GetString("PM_SP_Select_ComponentReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMGetEquipment.
        /// </summary>
        internal static string PM_SP_Select_Equipment {
            get {
                return ResourceManager.GetString("PM_SP_Select_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMGetMaintenancePlan.
        /// </summary>
        internal static string PM_SP_Select_MaintenancePlan {
            get {
                return ResourceManager.GetString("PM_SP_Select_MaintenancePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMGetMaterial.
        /// </summary>
        internal static string PM_SP_Select_Material {
            get {
                return ResourceManager.GetString("PM_SP_Select_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMGetMeasure.
        /// </summary>
        internal static string PM_SP_Select_Measure {
            get {
                return ResourceManager.GetString("PM_SP_Select_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMGetMeasurementDocument.
        /// </summary>
        internal static string PM_SP_Select_MeasurementDocument {
            get {
                return ResourceManager.GetString("PM_SP_Select_MeasurementDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMGetTask.
        /// </summary>
        internal static string PM_SP_Select_Task {
            get {
                return ResourceManager.GetString("PM_SP_Select_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMGetTechnicalLocation.
        /// </summary>
        internal static string PM_SP_Select_TechnicalLocation {
            get {
                return ResourceManager.GetString("PM_SP_Select_TechnicalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMGetTechnicalObject.
        /// </summary>
        internal static string PM_SP_Select_TechnicalObject {
            get {
                return ResourceManager.GetString("PM_SP_Select_TechnicalObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMGetWorkOrder.
        /// </summary>
        internal static string PM_SP_Select_WorkOrder {
            get {
                return ResourceManager.GetString("PM_SP_Select_WorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMUpdateActivity.
        /// </summary>
        internal static string PM_SP_Update_Activity {
            get {
                return ResourceManager.GetString("PM_SP_Update_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMUpdateAdvice.
        /// </summary>
        internal static string PM_SP_Update_Advice {
            get {
                return ResourceManager.GetString("PM_SP_Update_Advice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMUpdateComponentReplacement.
        /// </summary>
        internal static string PM_SP_Update_ComponentReplacement {
            get {
                return ResourceManager.GetString("PM_SP_Update_ComponentReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMUpdateEquipment.
        /// </summary>
        internal static string PM_SP_Update_Equipment {
            get {
                return ResourceManager.GetString("PM_SP_Update_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMUpdateMaintenancePlan.
        /// </summary>
        internal static string PM_SP_Update_MaintenancePlan {
            get {
                return ResourceManager.GetString("PM_SP_Update_MaintenancePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMUpdateMaterial.
        /// </summary>
        internal static string PM_SP_Update_Material {
            get {
                return ResourceManager.GetString("PM_SP_Update_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMUpdateMeasure.
        /// </summary>
        internal static string PM_SP_Update_Measure {
            get {
                return ResourceManager.GetString("PM_SP_Update_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMUpdateMeasurmentDocument.
        /// </summary>
        internal static string PM_SP_Update_MeasurementDocument {
            get {
                return ResourceManager.GetString("PM_SP_Update_MeasurementDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMUpdateTask.
        /// </summary>
        internal static string PM_SP_Update_Task {
            get {
                return ResourceManager.GetString("PM_SP_Update_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMUpdateTechnicalObject.
        /// </summary>
        internal static string PM_SP_Update_TechnicalObject {
            get {
                return ResourceManager.GetString("PM_SP_Update_TechnicalObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spPMUpdateWorkOrder.
        /// </summary>
        internal static string PM_SP_Update_WorkOrder {
            get {
                return ResourceManager.GetString("PM_SP_Update_WorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSCSMAddParameterForCategory.
        /// </summary>
        internal static string SCMS_SP_AddParameterForCategory {
            get {
                return ResourceManager.GetString("SCMS_SP_AddParameterForCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSCMSCreateUser.
        /// </summary>
        internal static string SCMS_SP_AddUser {
            get {
                return ResourceManager.GetString("SCMS_SP_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSCMSAuthorize.
        /// </summary>
        internal static string SCMS_SP_Authorize {
            get {
                return ResourceManager.GetString("SCMS_SP_Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSCMSGetMobileAppMenuItems.
        /// </summary>
        internal static string SCMS_SP_GetMobileAppMenuItems {
            get {
                return ResourceManager.GetString("SCMS_SP_GetMobileAppMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSCMSGetToken.
        /// </summary>
        internal static string SCMS_SP_GetToken {
            get {
                return ResourceManager.GetString("SCMS_SP_GetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSCMSUpdateParameterForCategory.
        /// </summary>
        internal static string SCMS_SP_UpdateParameterForCategory {
            get {
                return ResourceManager.GetString("SCMS_SP_UpdateParameterForCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSRAGetEmployeeIdForPermitsAndAbsences.
        /// </summary>
        internal static string SRA_SP_EmployeeIdForPermitsAndAbsences {
            get {
                return ResourceManager.GetString("SRA_SP_EmployeeIdForPermitsAndAbsences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSRAGetEmployeeActivitiesForApproval.
        /// </summary>
        internal static string SRA_SP_GetEmployeeActivitiesForApproval {
            get {
                return ResourceManager.GetString("SRA_SP_GetEmployeeActivitiesForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSRAGetEmployeeActivitiesInPeriod.
        /// </summary>
        internal static string SRA_SP_GetEmployeeActivitiesInPeriod {
            get {
                return ResourceManager.GetString("SRA_SP_GetEmployeeActivitiesInPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSRAGetEmployeeById.
        /// </summary>
        internal static string SRA_SP_GetEmployeeById {
            get {
                return ResourceManager.GetString("SRA_SP_GetEmployeeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSRAGetEmployeeByToken.
        /// </summary>
        internal static string SRA_SP_GetEmployeeForToken {
            get {
                return ResourceManager.GetString("SRA_SP_GetEmployeeForToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSCMSGetParametersByCategory.
        /// </summary>
        internal static string SRA_SP_GetParametersByCategory {
            get {
                return ResourceManager.GetString("SRA_SP_GetParametersByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSRAInsertPermitsAndAbsences.
        /// </summary>
        internal static string SRA_SP_Insert_PermitsAndAbsences {
            get {
                return ResourceManager.GetString("SRA_SP_Insert_PermitsAndAbsences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSRAInsertEmployeeActivity.
        /// </summary>
        internal static string SRA_SP_InsertEmployeeActivity {
            get {
                return ResourceManager.GetString("SRA_SP_InsertEmployeeActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSRAUpdatePermitsAndAbsences.
        /// </summary>
        internal static string SRA_SP_Update_PermitsAndAbsences {
            get {
                return ResourceManager.GetString("SRA_SP_Update_PermitsAndAbsences", resourceCulture);
            }
        }
    }
}
