CREATE FUNCTION [dbo].[fnCheckGender]
(
	@gender nvarchar(1)
)
RETURNS BIT
AS
BEGIN
	IF EXISTS(SELECT [TBL_SCMS_PARAM].value
				FROM [TBL_SCMS_PARAM] 
					INNER JOIN [TBL_SCMS_PARAM_CATEGORY] ON [TBL_SCMS_PARAM_CATEGORY].id = [TBL_SCMS_PARAM].category 
						AND [TBL_SCMS_PARAM_CATEGORY].name = 'SRA_SOFTTEK_PERSON_GENDER'
				WHERE [TBL_SCMS_PARAM].value = @gender)
		RETURN 1
	RETURN 0 
END
