CREATE FUNCTION [dbo].[fnSRACheckPermitsAndAbsencesCode]
(
	@activity_code int
)
RETURNS BIT
AS

BEGIN

	IF EXISTS(SELECT [TBL_SCMS_PARAM].id
				FROM [TBL_SCMS_PARAM] 
				INNER JOIN [TBL_SCMS_PARAM_CATEGORY] ON [TBL_SCMS_PARAM_CATEGORY].id = [TBL_SCMS_PARAM].category 
				AND ([TBL_SCMS_PARAM_CATEGORY].name = 'SRA_PERMITS_AND_ABSENCES')
				WHERE [TBL_SCMS_PARAM].id = @activity_code)
		RETURN 1
	RETURN 0 
END
