CREATE FUNCTION [dbo].[fnSRACheckActivityCode]
(
	@project nvarchar(20),
	@activity_code nvarchar(10)
)
RETURNS BIT
AS

BEGIN

	IF EXISTS(SELECT [TBL_SCMS_PARAM].value
				FROM [TBL_SCMS_PARAM] 
					INNER JOIN [TBL_SCMS_PARAM_CATEGORY] ON [TBL_SCMS_PARAM_CATEGORY].id = [TBL_SCMS_PARAM].category 
						AND ([TBL_SCMS_PARAM_CATEGORY].name = 'SRA_SOFTTEK_PROJECT_ACTIVITIES'
						OR  (@project = (SELECT TOP 1 [TBL_SCMS_PARAM].value FROM [TBL_SCMS_PARAM] INNER JOIN [TBL_SCMS_PARAM_CATEGORY] ON [TBL_SCMS_PARAM_CATEGORY].id = [TBL_SCMS_PARAM].category AND [TBL_SCMS_PARAM_CATEGORY].name = 'SRA_PNOCH_PROJECT_CODE') 
							AND [TBL_SCMS_PARAM_CATEGORY].name = 'SRA_SOFTTEK_PNOCH_ACTIVITIES'))
				WHERE [TBL_SCMS_PARAM].value = @activity_code)
		RETURN 1
	RETURN 0 
END
